### PR TITLE
Expose all the options avaiable when instantiate the map and map url parameters

### PR DESCRIPTION
**Pull request by monaye**
Thank you for beautifully organized code. 

This PR contains following 
1. Allow user to pass any options when instantiate the map and autocomplete 
2. Allow user to pass any parameters to map api url 
3. refactor initialization of settings to auto mapping
4. organized methods in the MapsAddress to alphabetically 

Please let me know if there is anything you want me to change.

### CODE REVIEW

**Comment by mauricewijnia** [comment]
Hi,

Thanks for your PR!

Could you remove the console.log that's left in `getUrlParamsFromObj()`.
And if it's not too much to ask, could you add some examples to the README including the links that you added to the code?

Code is looking good otherwise! So I'll definitely merge when you're done :)

**Comment by monaye** [comment]
Hello, 

Thank you for considering. 

1. Added usage to the reademe
2. Added `address_components` to the return json obj to save in the db  (b/c it didn't contained all the address for my country)
3. Added allow user to add options for geocoder

**Comment by monaye** [comment]
Sorry, feature creeping... w 

1. Added allow user to disable map click to get address

**Comment by mauricewijnia** [comment]
Thanks that's perfect, merging now :)

**Pull request merged**
